version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table contain Airbnb listings
    columns: 

      - name: listing_id
        description: PK for listings
        tests: 
         - unique
         - not_null

      - name: host_id
        description: References host table
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: type of room
        tests:
          - accepted_values:
              values: ['Entire home/apt','Private room','Shared room','Hotel room']

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        tests:
          - positive_value

  - name: dim_hosts_cleansed
    description: Cleansed table contain Airbnb hostings
    columns:
      - name: is_superhost
        desciption: specifies superhost or not
        
      - name: host_id
        description: specifies host id - unique
        tests: 
         - unique
  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .995
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn